import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, DateTime
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.database import Base

class Template(Base):
    __tablename__ = "templates"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    source_file = Column(String(255))
    schema_json = Column(JSONB, nullable=False) # sections, slots, styles
    html_content = Column(Text) # Jinja2 code generated by AI
    preview_html = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    @property
    def layout_json(self):
        return self.schema_json
        
    @layout_json.setter
    def layout_json(self, value):
        self.schema_json = value
