"""add_raw_text_to_candidates

Revision ID: 1bc1520e803e
Revises: 8361bd964980
Create Date: 2026-07-14 09:10:30.761412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc1520e803e'
down_revision: Union[str, None] = '8361bd964980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'raw_text')
    # ### end Alembic commands ###
