"""Fix null characters issue or update schema

Revision ID: f3a7abee3fff
Revises: 1bc1520e803e
Create Date: 2026-07-16 04:11:27.914774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a7abee3fff'
down_revision: Union[str, None] = '1bc1520e803e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration was generated to adapt to the psycopg2.errors.UntranslatableCharacter issue.
    # The actual fix is handled in the application layer (tasks.py) by sanitizing 
    # null bytes (\u0000) from parsed PDF strings before inserting into the JSONB column.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
